In [1]:
# step-1
# importing libraries
import pandas as pd

In [2]:
# step-2
# reading/importing dataset
pd.read_excel("pandas_01_day6.xlsx")

   Height Weight Favourite Dish
0     5.8    101  Chicken Pulao
1     6.2     92        Biryani
2     5.9     62  Karahi Ghosht
3     5.9     95  Chicken Pulao
4     5.9     55  Chicken Pulao
..    ...    ...            ...
82    5.4     55          Pasta
83    5.9   75KG  Karahi Ghosht
84    5.4     61        Biryani
85    6.2     68  Chicken Pulao
86    5.1     96        Biryani

[87 rows x 3 columns]

In [7]:
df=pd.read_excel("pandas_01_day6.xlsx")

In [8]:
print(df)

   Height Weight Favourite Dish
0     5.8    101  Chicken Pulao
1     6.2     92        Biryani
2     5.9     62  Karahi Ghosht
3     5.9     95  Chicken Pulao
4     5.9     55  Chicken Pulao
..    ...    ...            ...
82    5.4     55          Pasta
83    5.9   75KG  Karahi Ghosht
84    5.4     61        Biryani
85    6.2     68  Chicken Pulao
86    5.1     96        Biryani

[87 rows x 3 columns]

In [9]:
df

   Height Weight Favourite Dish
0     5.8    101  Chicken Pulao
1     6.2     92        Biryani
2     5.9     62  Karahi Ghosht
3     5.9     95  Chicken Pulao
4     5.9     55  Chicken Pulao
..    ...    ...            ...
82    5.4     55          Pasta
83    5.9   75KG  Karahi Ghosht
84    5.4     61        Biryani
85    6.2     68  Chicken Pulao
86    5.1     96        Biryani

[87 rows x 3 columns]

In [10]:
df.head()

  Height Weight Favourite Dish
0    5.8    101  Chicken Pulao
1    6.2     92        Biryani
2    5.9     62  Karahi Ghosht
3    5.9     95  Chicken Pulao
4    5.9     55  Chicken Pulao

In [11]:
df.shape

(87, 3)

In [12]:
df.info

<bound method DataFrame.info of    Height Weight Favourite Dish
0     5.8    101  Chicken Pulao
1     6.2     92        Biryani
2     5.9     62  Karahi Ghosht
3     5.9     95  Chicken Pulao
4     5.9     55  Chicken Pulao
..    ...    ...            ...
82    5.4     55          Pasta
83    5.9   75KG  Karahi Ghosht
84    5.4     61        Biryani
85    6.2     68  Chicken Pulao
86    5.1     96        Biryani

[87 rows x 3 columns]>

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Height          87 non-null     object
 1   Weight          87 non-null     object
 2   Favourite Dish  87 non-null     object
dtypes: object(3)
memory usage: 2.2+ KB